### ISSUE TITLE
data package draft post

### ISSUE THREAD

**Issue by apreshill** [rbind/apreshill#2]
Raw R Markdown:

https://github.com/rbind/apreshill/blob/data-package-post/content/post/2018-06-29-data-package.Rmd

Can be viewed here!

https://5b8d90fab13fb108849d1b3a--apreshill.netlify.com/post/data-package/

@ismayc
@isteves

**Comment by ismayc** [comment]
Cool! Can you direct us to the Rmd file so we can make tweaks/add suggestions too?

**Comment by ismayc** [comment]
Sounds like a good blogpost follow-up is in order when the package is on CRAN too? 😄

**Comment by isteves** [comment]
Neat, thanks for sharing!  Btw, if you haven't seen [Tomas](https://r-mageddon.netlify.com/post/writing-an-r-package-from-scratch/) and [Emil](https://www.hvitfeldt.me/2018/09/usethis-workflow-for-package-development/)'s usethis blogposts, they're worth checking out.

A few initial comments/questions:

1. In the next release, devtools will become a "meta-package" (like the tidyverse) that will install usethis and friends as a bundle (see [conscious uncoupling](https://github.com/r-lib/devtools#conscious-uncoupling)).  Is this TMI or is it worth mentioning in the post?  This means that eventually, users can install everything with `install.packages("devtools")` and possibly also load everything with `library(devtools)`. Currently, both `usethis::use_*` and `devtools::use_*` work, but eventually `devtools::use_*` will be deprecated.

2. In Windows, I get an error when trying to use `create_from_github`.  

![image](https://user-images.githubusercontent.com/25118334/45020983-119e1f80-b039-11e8-88c7-93415f54f252.png)

This [RStudio Community thread](https://community.rstudio.com/t/difficulty-using-usethis-use-github/5579/7) discusses some of these git/R issues on Windows and Mac, and provides good troubleshooting tips.  This [workaround from Jenny](http://happygitwithr.com/ssh-keys.html#git2r-or-some-other-tool-cant-find-ssh-keys-on-windows) worked for me and may be worth mentioning (or at least linking to):

```r
cred <- git2r::cred_ssh_key(
  publickey = "~/../.ssh/id_rsa.pub",
  privatekey = "~/../.ssh/id_rsa"
)
use_github(credentials = cred)
# or in this case, create_from_github("apreshill/bakeoff", credentials = cred)
```

Also, Tomas/Emil both use `use_git` and `use_github`, which saves the step of visiting github.com.  Perhaps it's also worth using it in this post?  (Though I do like seeing this alternative workflow!)

3. 😀 nice example of `purrr::walk`!  I never know when to use it, so it's great to see it in action!

4. Rather than using `roxygen2::roxygenise`, I typically use `devtools::document`, which is really just a wrapper around the former.  My preference would be to stick with `devtools` simply because it makes one less package that the reader has to think about.  In any case, it already shows up in a [screenshot](https://5b8d90fab13fb108849d1b3a--apreshill.netlify.com/post/2018-06-29-data-package_files/first-build.png)!

Looking forward to our chat later today!

**Comment by ismayc** [comment]
@ismayc will add TL; DR
